language: java
jdk:
  - oraclejdk8
before_install:
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r24.1.2-linux.tgz
  - tar -zxf android-sdk_r24.1.2-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter 1,2,21 --no-ui --force
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/996f1afd70df12c9e77b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false